version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=linkGenerator
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/.local/lib/db/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local



